// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: pkg/whatsup.proto

package whatsup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_pkg_whatsup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whatsup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_pkg_whatsup_proto_rawDescGZIP(), []int{0}
}

func (x *Success) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []string               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_pkg_whatsup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whatsup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_pkg_whatsup_proto_rawDescGZIP(), []int{1}
}

func (x *UserList) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUser    string                 `protobuf:"bytes,1,opt,name=source_user,json=sourceUser,proto3" json:"source_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_pkg_whatsup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whatsup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_pkg_whatsup_proto_rawDescGZIP(), []int{2}
}

func (x *Registration) GetSourceUser() string {
	if x != nil {
		return x.SourceUser
	}
	return ""
}

type AuthToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	mi := &file_pkg_whatsup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whatsup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_pkg_whatsup_proto_rawDescGZIP(), []int{3}
}

func (x *AuthToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_whatsup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whatsup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_whatsup_proto_rawDescGZIP(), []int{4}
}

var File_pkg_whatsup_proto protoreflect.FileDescriptor

const file_pkg_whatsup_proto_rawDesc = "" +
	"\n" +
	"\x11pkg/whatsup.proto\x12\awhatsup\"\x19\n" +
	"\aSuccess\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\" \n" +
	"\bUserList\x12\x14\n" +
	"\x05users\x18\x01 \x03(\tR\x05users\"/\n" +
	"\fRegistration\x12\x1f\n" +
	"\vsource_user\x18\x01 \x01(\tR\n" +
	"sourceUser\"!\n" +
	"\tAuthToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\a\n" +
	"\x05Empty2\x9a\x01\n" +
	"\aWhatsUp\x124\n" +
	"\aConnect\x12\x15.whatsup.Registration\x1a\x12.whatsup.AuthToken\x12)\n" +
	"\x04List\x12\x0e.whatsup.Empty\x1a\x11.whatsup.UserList\x12.\n" +
	"\n" +
	"Disconnect\x12\x0e.whatsup.Empty\x1a\x10.whatsup.SuccessB\x11Z\x0fwhatsup/whatsupb\x06proto3"

var (
	file_pkg_whatsup_proto_rawDescOnce sync.Once
	file_pkg_whatsup_proto_rawDescData []byte
)

func file_pkg_whatsup_proto_rawDescGZIP() []byte {
	file_pkg_whatsup_proto_rawDescOnce.Do(func() {
		file_pkg_whatsup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_whatsup_proto_rawDesc), len(file_pkg_whatsup_proto_rawDesc)))
	})
	return file_pkg_whatsup_proto_rawDescData
}

var file_pkg_whatsup_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_whatsup_proto_goTypes = []any{
	(*Success)(nil),      // 0: whatsup.Success
	(*UserList)(nil),     // 1: whatsup.UserList
	(*Registration)(nil), // 2: whatsup.Registration
	(*AuthToken)(nil),    // 3: whatsup.AuthToken
	(*Empty)(nil),        // 4: whatsup.Empty
}
var file_pkg_whatsup_proto_depIdxs = []int32{
	2, // 0: whatsup.WhatsUp.Connect:input_type -> whatsup.Registration
	4, // 1: whatsup.WhatsUp.List:input_type -> whatsup.Empty
	4, // 2: whatsup.WhatsUp.Disconnect:input_type -> whatsup.Empty
	3, // 3: whatsup.WhatsUp.Connect:output_type -> whatsup.AuthToken
	1, // 4: whatsup.WhatsUp.List:output_type -> whatsup.UserList
	0, // 5: whatsup.WhatsUp.Disconnect:output_type -> whatsup.Success
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_whatsup_proto_init() }
func file_pkg_whatsup_proto_init() {
	if File_pkg_whatsup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_whatsup_proto_rawDesc), len(file_pkg_whatsup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_whatsup_proto_goTypes,
		DependencyIndexes: file_pkg_whatsup_proto_depIdxs,
		MessageInfos:      file_pkg_whatsup_proto_msgTypes,
	}.Build()
	File_pkg_whatsup_proto = out.File
	file_pkg_whatsup_proto_goTypes = nil
	file_pkg_whatsup_proto_depIdxs = nil
}
